# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
before_script:
  # - julia -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/ryanelandt/NumericalTricks.jl.git"))'
  # - julia -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/ryanelandt/Tri_Tet_Intersections.jl.git"))'
  # - julia -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/ryanelandt/Binary_BB_Trees.jl.git"))'
  # - julia -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/ryanelandt/Radau.jl.git"))'
  # - julia -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl.git"))'

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: Documentation
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
  after_success: skip
